version: '3'

services:
  app:
    #container_name: redis-test
    image: redis-test
    container_name: shiny_app
    build:
      context: .
      #dockerfile: Dockerfile
    restart: on-failure
    user: root
    command: ["usr/bin/shiny-server.sh"]
    ports:
      - '3838:3838'
    volumes:
    - ./app:/srv/shiny-server/app
    # depends_on:
    #   -  mysql_db
    network_mode: host
    environment:
      - REDIS_URL=redis://cache
    
  mysql_db:
    image: mysql:latest
    container_name: user_db
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql" # for persistent storage
    ports:
      - '3306:3306'
    expose:
      - '3306'
    restart: always
    cap_add:
      - SYS_NICE
    environment: 
      - MYSQL_ROOT_PASSWORD=pippo
      - MYSQL_DATABASE=shiny_app
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=mypwd
    network_mode: host
    
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes: 
      - "./data/redis:/redis"
    restart: always
    network_mode: host


volumes:
  app:
  mysql_db:
  redis:
